version: "3.3"
services:
  server:
    build: .
    container_name: node-server
    image: node-server
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - mongo
      - mongo-express
  mongo:
    image: mongo
    networks:
      - backend
    ports:
      - "27017:27017"
    name: db
    environment:
      "MONGO_INITDB_ROOT_USERNAME": root
      "MONGO_INITDB_ROOT_PASSWORD": F235vk26
  mongo-express:
    image: mongo-express
    networks:
      - backend
    ports:
      - "8081:8081"
    name: mongo-express
    environment:
      "ME_CONFIG_MONGODB_SERVER": db
      "ME_CONFIG_BASICAUTH_USERNAME": root
      "ME_CONFIG_BASICAUTH_PASSWORD": F235vk26
    depends_on:
      - mongo
networks:
  backend:
